#!/usr/bin/env python3
"""
Enhanced installer for Claude-Gemini Delegation
- Auto-detects installed CLIs
- Interactive CLI selection
- Copies hook files automatically
- Generates custom routing rules
- Creates wrapper scripts

Usage:
    python install-enhanced.py
"""

import os
import sys
import json
import shutil
import argparse
import datetime
import subprocess
from pathlib import Path
from typing import Dict, Set
import stat

# Import the basic installer classes
from pathlib import Path

class Colors:
    HEADER = '\033[95m'
    BLUE = '\033[94m'
    GREEN = '\033[92m'
    YELLOW = '\033[93m'
    RED = '\033[91m'
    END = '\033[0m'
    BOLD = '\033[1m'

def print_header(text: str):
    print(f"\n{Colors.HEADER}{Colors.BOLD}{'=' * 60}")
    print(f"  {text}")
    print(f"{'=' * 60}{Colors.END}\n")

def print_success(text: str):
    print(f"{Colors.GREEN}[SUCCESS] {text}{Colors.END}")

def print_error(text: str):
    print(f"{Colors.RED}[ERROR] {text}{Colors.END}")

def print_warning(text: str):
    print(f"{Colors.YELLOW}[WARNING] {text}{Colors.END}")

def print_info(text: str):
    print(f"{Colors.BLUE}[INFO] {text}{Colors.END}")

# Assume hook templates are in same directory as installer
SCRIPT_DIR = Path(__file__).parent
HOOKS_SOURCE = SCRIPT_DIR / "hooks"
AGENTS_SOURCE = SCRIPT_DIR / "agents"
DEFAULT_GEMINI_MODEL = "gemini-3-flash-preview"
ROOT_CLAUDE_IMPORTS = ("@AGENTS.md",)
GEMINI_DELEGATION_DIR = ".gemini-delegation"

SHARED_HOOK_SCRIPTS = [
    "gemini_delegate.py",
    "pre_delegate.py",
    "post_delegate.py",
    "analyze_metrics.py",
    "delegation_guard.py",
    "delegation_guard.ps1",
    "delegate_and_log.ps1",
    "delegate",
    "delegate.ps1",
    "delegate.bat",
]


def install_agents(project_dir: Path):
    """Copy bundled agent definitions (e.g. Dave) into the target project."""
    if not AGENTS_SOURCE.exists():
        return

    dest_agents = project_dir / "agents"
    copied = 0
    for agent_dir in AGENTS_SOURCE.iterdir():
        if not agent_dir.is_dir():
            continue
        dest = dest_agents / agent_dir.name
        dest.mkdir(parents=True, exist_ok=True)
        for f in agent_dir.iterdir():
            if f.is_file():
                shutil.copy2(f, dest / f.name)
                if os.name != "nt" and f.suffix in (".sh", ".ps1", ""):
                    (dest / f.name).chmod(
                        (dest / f.name).stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH
                    )
                copied += 1
        print_success(f"Installed agent: {agent_dir.name}")

    if copied:
        # Ignore audit reports generated by agents
        gitignore = project_dir / ".gitignore"
        entry = "audit/"
        if gitignore.exists():
            if entry not in gitignore.read_text(encoding="utf-8"):
                with gitignore.open("a", encoding="utf-8") as fh:
                    fh.write(f"\n# Agent audit reports\n{entry}\n")
        else:
            gitignore.write_text(f"# Agent audit reports\n{entry}\n", encoding="utf-8")


def ensure_temp_dir(project_dir: Path) -> Path:
    """Create temp/ for delegation response files and update .gitignore."""
    temp_dir = project_dir / "temp"
    temp_dir.mkdir(exist_ok=True)
    gitkeep = temp_dir / ".gitkeep"
    if not gitkeep.exists():
        gitkeep.touch()

    gitignore = project_dir / ".gitignore"
    ignore_entry = "temp/gemini-*.md"
    if gitignore.exists():
        content = gitignore.read_text(encoding="utf-8")
        if ignore_entry not in content:
            with gitignore.open("a", encoding="utf-8") as f:
                f.write(f"\n# Delegation response files\n{ignore_entry}\n")
    else:
        gitignore.write_text(f"# Delegation response files\n{ignore_entry}\n", encoding="utf-8")

    print_success(f"Created temp/ at {temp_dir}")
    return temp_dir


def stage_generated_files(project_dir: Path, base_dir: Path, codex_dir: Path):
    """Stage all installer-generated files with git if project is a git repo."""
    try:
        probe = subprocess.run(
            ["git", "rev-parse", "--git-dir"],
            cwd=str(project_dir),
            capture_output=True,
            timeout=5,
        )
        if probe.returncode != 0:
            return
    except (OSError, subprocess.TimeoutExpired):
        return

    rel = lambda p: str(p.relative_to(project_dir))

    paths = [
        "AGENTS.md",
        "CLAUDE.md",
        ".gitignore",
        "temp/.gitkeep",
        rel(base_dir),
        rel(codex_dir),
        ".gemini-delegation/",
    ]

    print_header("Staging Generated Files")
    staged = []
    for p in paths:
        try:
            r = subprocess.run(
                ["git", "add", p],
                cwd=str(project_dir),
                capture_output=True,
                timeout=5,
            )
            if r.returncode == 0:
                staged.append(p)
                print_success(f"git add {p}")
        except (OSError, subprocess.TimeoutExpired):
            pass

    if staged:
        print_info(f"Staged {len(staged)} path(s). Run `git commit` when ready.")
    else:
        print_warning("Nothing staged (no changes or git not available).")


def get_registry_path() -> Path:
    """Get the path to the global installation registry."""
    return Path.home() / ".gemini-delegation-registry.json"


def load_registry() -> Set[str]:
    """Load the set of installed project directories from the global registry."""
    registry_path = get_registry_path()
    if not registry_path.exists():
        return set()
    try:
        data = json.loads(registry_path.read_text(encoding="utf-8"))
        return set(data.get("installations", []))
    except (json.JSONDecodeError, OSError):
        print_warning(f"Failed to read registry at {registry_path}. Starting fresh.")
        return set()


def save_registry(installations: Set[str]):
    """Save the set of installed project directories to the global registry."""
    registry_path = get_registry_path()
    data = {"installations": sorted(list(installations))}
    try:
        registry_path.write_text(json.dumps(data, indent=2), encoding="utf-8")
    except OSError as e:
        print_warning(f"Failed to write registry to {registry_path}: {e}")


def register_installation(project_dir: Path):
    """Add a project directory to the global registry."""
    installations = load_registry()
    abs_path = str(project_dir.resolve())
    if abs_path not in installations:
        installations.add(abs_path)
        save_registry(installations)
        print_info(f"Registered installation at: {abs_path}")


def update_all_installations(source_hooks: Path):
    """Update hook scripts in all registered installations."""
    print_header("Updating All Registered Installations")
    installations = load_registry()
    if not installations:
        print_info("No installations found in registry.")
        return

    valid_installations = set()
    updated_count = 0

    for path_str in installations:
        project_dir = Path(path_str)
        if not project_dir.exists() or not project_dir.is_dir():
            print_warning(f"Project directory no longer exists: {path_str}")
            continue
        
        gem_dir = project_dir / GEMINI_DELEGATION_DIR
        hooks_dir = gem_dir / "hooks"
        
        if not hooks_dir.exists():
            print_warning(f"Hooks directory missing in {path_str}, skipping update.")
            continue

        valid_installations.add(path_str)
        print_info(f"Updating: {path_str}")

        for script in SHARED_HOOK_SCRIPTS:
            src = source_hooks / script
            if not src.exists():
                continue
            dest = hooks_dir / script
            shutil.copy2(src, dest)
            if os.name != "nt":
                dest.chmod(dest.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)

        # Rewrite shared wrappers in case logic changed
        _write_gemini_delegation_wrappers(hooks_dir)

        # Refresh per-env shims and settings guards for .claude and .Codex
        for env_dir_name in (".claude", ".Codex"):
            env_dir = project_dir / env_dir_name
            if env_dir.exists():
                create_env_shims(env_dir / "hooks")
                create_claude_settings(env_dir)

        # Ensure temp/ exists (no-op if already present)
        ensure_temp_dir(project_dir)
        updated_count += 1
        
    # Clean up registry
    if len(valid_installations) != len(installations):
        save_registry(valid_installations)
        print_info("Cleaned up missing directories from registry.")
        
    print_success(f"Successfully updated {updated_count} installation(s).")


def install_gemini_delegation_dir(project_dir: Path, config: dict):
    """Install the shared .gemini-delegation/ directory with all hook scripts."""
    gem_dir = project_dir / GEMINI_DELEGATION_DIR
    hooks_dir = gem_dir / "hooks"
    metrics_dir = gem_dir / "metrics"

    print_header("Installing Shared .gemini-delegation/ Directory")
    hooks_dir.mkdir(parents=True, exist_ok=True)
    metrics_dir.mkdir(parents=True, exist_ok=True)

    for script in SHARED_HOOK_SCRIPTS:
        src = HOOKS_SOURCE / script
        if not src.exists():
            print_warning(f"{script} not found in source, skipping")
            continue
        dest = hooks_dir / script
        shutil.copy2(src, dest)
        if os.name != "nt":
            dest.chmod(dest.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
        print_success(f"Installed {script}")

    # Generate the delegate/delegate.bat/delegate wrapper scripts in-place
    # so .gemini-delegation/hooks/delegate.ps1 → pre_delegate.py etc. work.
    _write_gemini_delegation_wrappers(hooks_dir)

    config_path = gem_dir / "delegation_config.json"
    with config_path.open("w", encoding="utf-8") as f:
        json.dump(config, f, indent=2)
    print_success(f"Saved config to {config_path}")
    
    # Register installation globally
    register_installation(project_dir)


def _write_gemini_delegation_wrappers(hooks_dir: Path):
    """Write the main delegate wrapper scripts into .gemini-delegation/hooks/."""
    unix = hooks_dir / "delegate"
    unix.write_text(
        '#!/bin/bash\nSCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"\n'
        'python3 "$SCRIPT_DIR/pre_delegate.py" "$@"\n',
        encoding="utf-8",
    )
    if os.name != "nt":
        unix.chmod(unix.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)

    (hooks_dir / "delegate.bat").write_text(
        "@echo off\n"
        'set "SCRIPT_DIR=%~dp0"\n'
        'py -3 "%SCRIPT_DIR%pre_delegate.py" %*\n',
        encoding="utf-8",
    )

    (hooks_dir / "delegate.ps1").write_text(
        "[CmdletBinding()]\n"
        "param(\n"
        "    [Parameter(ValueFromPipeline=$true, Position=0)][string]$Task,\n"
        "    [Parameter(Position=1)][string]$Context = 'General task',\n"
        "    [Parameter(Position=2)][int]$MaxLines = 0\n"
        ")\n"
        "$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path\n"
        "$PythonCommands = @(\n"
        "    @{ Command = 'py'; Prefix = @('-3') },\n"
        "    @{ Command = 'python3'; Prefix = @() },\n"
        "    @{ Command = 'python'; Prefix = @() }\n"
        ")\n"
        "foreach ($Python in $PythonCommands) {\n"
        "    if (-not (Get-Command $Python.Command -ErrorAction SilentlyContinue)) { continue }\n"
        "    & $Python.Command @($Python.Prefix + @('-c', 'import sys; sys.exit(0 if sys.version_info[0] >= 3 else 1)')) *> $null\n"
        "    if ($LASTEXITCODE -ne 0) { continue }\n"
        "    $argsToPass = @(\"$ScriptDir/pre_delegate.py\", \"-\", $Context)\n"
        "    if ($MaxLines -gt 0) { $argsToPass += $MaxLines }\n"
        "    $Task | & $Python.Command @($Python.Prefix + $argsToPass)\n"
        "    exit $LASTEXITCODE\n"
        "}\n"
        "Write-Error 'Python 3 was not found.'\n"
        "exit 127\n",
        encoding="utf-8",
    )
    print_success("Created .gemini-delegation wrapper scripts (delegate, delegate.bat, delegate.ps1)")


def create_env_shims(hooks_dir: Path):
    """Create thin per-environment shims that forward to .gemini-delegation/hooks/."""
    print_header("Creating Wrapper Scripts")
    hooks_dir.mkdir(parents=True, exist_ok=True)

    # delegate (unix)
    shim = hooks_dir / "delegate"
    shim.write_text(
        '#!/bin/bash\n'
        'SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"\n'
        'PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"\n'
        'exec "$PROJECT_ROOT/.gemini-delegation/hooks/delegate" "$@"\n',
        encoding="utf-8",
    )
    if os.name != "nt":
        shim.chmod(shim.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    print_success("Created Unix wrapper: delegate")

    # delegate.bat
    (hooks_dir / "delegate.bat").write_text(
        "@echo off\n"
        'for %%I in ("%~dp0..\\..") do set "PROJECT_ROOT=%%~fI"\n'
        'call "%PROJECT_ROOT%\\.gemini-delegation\\hooks\\delegate.bat" %*\n',
        encoding="utf-8",
    )
    print_success("Created Windows wrapper: delegate.bat")

    # delegate.ps1
    (hooks_dir / "delegate.ps1").write_text(
        "$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path\n"
        '$ProjectRoot = [System.IO.Path]::GetFullPath((Join-Path $ScriptDir "..\\.."))\n'
        '$input | & (Join-Path $ProjectRoot ".gemini-delegation\\hooks\\delegate.ps1") @args\n'
        "exit $LASTEXITCODE\n",
        encoding="utf-8",
    )
    print_success("Created PowerShell wrapper: delegate.ps1")

    # delegate_and_log.ps1
    (hooks_dir / "delegate_and_log.ps1").write_text(
        "[CmdletBinding()]\n"
        "param(\n"
        "    [Parameter(Mandatory = $true, Position = 0)][string]$Task,\n"
        "    [Parameter(Position = 1)][string]$Context = 'General task',\n"
        "    [Parameter(Position = 2)][int]$MaxLines = 0,\n"
        "    [ValidateSet('default', 'research')]\n"
        "    [string]$Profile = 'default'\n"
        ")\n"
        "$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path\n"
        '$ProjectRoot = [System.IO.Path]::GetFullPath((Join-Path $ScriptDir "..\\.."))\n'
        '& (Join-Path $ProjectRoot ".gemini-delegation\\hooks\\delegate_and_log.ps1") `\n'
        "    -Task $Task -Context $Context -MaxLines $MaxLines -Profile $Profile\n"
        "exit $LASTEXITCODE\n",
        encoding="utf-8",
    )
    print_success("Created PowerShell wrapper: delegate_and_log.ps1")

    # delegation_guard.ps1 (sets DELEGATION_HOOK_PREFIX for correct GUIDANCE text)
    env_dir_name = hooks_dir.parent.name  # ".claude" or ".Codex"
    (hooks_dir / "delegation_guard.ps1").write_text(
        "$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path\n"
        '$ProjectRoot = [System.IO.Path]::GetFullPath((Join-Path $ScriptDir "..\\.."))\n'
        f'$env:DELEGATION_HOOK_PREFIX = "{env_dir_name}/hooks"\n'
        "$InputPayload = [Console]::In.ReadToEnd()\n"
        '$InputPayload | & (Join-Path $ProjectRoot ".gemini-delegation\\hooks\\delegation_guard.ps1")\n'
        "exit $LASTEXITCODE\n",
        encoding="utf-8",
    )
    print_success("Created PowerShell wrapper: delegation_guard.ps1")


def copy_hook_files(dest_dir: Path):
    """Copy hook scripts to destination directory."""
    print_header("Installing Hook Scripts")
    
    hooks_to_copy = [
        "pre_delegate.py",
        "post_delegate.py",
        "analyze_metrics.py",
        "gemini_delegate.py",
        "delegation_guard.py",
        "delegation_guard.ps1",
        "delegate_and_log.ps1",
        "delegate",
        "delegate.ps1",
        "delegate.bat",
    ]
    
    copied_count = 0
    for hook_file in hooks_to_copy:
        source = HOOKS_SOURCE / hook_file
        dest = dest_dir / hook_file
        
        if not source.exists():
            print_warning(f"{hook_file} not found in source, skipping")
            continue
        
        shutil.copy2(source, dest)
        
        # Make executable on Unix
        if os.name != 'nt':
            dest.chmod(dest.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
        
        print_success(f"Installed {hook_file}")
        copied_count += 1
    
    if copied_count == 0:
        print_error("No hook files found to copy")
        print_info("Make sure hook scripts are in the 'hooks/' directory")
        return False
    
    return True


def create_wrapper_scripts(hooks_dir: Path, platform: str = None):
    """Create platform-specific wrapper scripts."""
    if platform is None:
        platform = "windows" if os.name == 'nt' else "unix"
    
    print_header("Creating Wrapper Scripts")
    
    # Bash wrapper. Create it on every platform so projects copied between
    # Windows, WSL, macOS, and Linux keep a complete hook set.
    wrapper = hooks_dir / "delegate"
    wrapper.write_text("""#!/bin/bash
# Delegation wrapper script
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
python3 "$SCRIPT_DIR/pre_delegate.py" "$@"
""", encoding="utf-8")
    if platform == "unix":
        wrapper.chmod(wrapper.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    print_success("Created Unix wrapper: delegate")
    
    # Windows batch
    wrapper_bat = hooks_dir / "delegate.bat"
    wrapper_bat.write_text("""@echo off
REM Delegation wrapper script
where py >nul 2>nul
if %errorlevel%==0 (
  py -3 -c "import sys; sys.exit(0 if sys.version_info[0] >= 3 else 1)" >nul 2>nul
  if %errorlevel%==0 (
    py -3 "%~dp0pre_delegate.py" %*
    exit /b %errorlevel%
  )
)

where python3 >nul 2>nul
if %errorlevel%==0 (
  python3 -c "import sys; sys.exit(0 if sys.version_info[0] >= 3 else 1)" >nul 2>nul
  if %errorlevel%==0 (
    python3 "%~dp0pre_delegate.py" %*
    exit /b %errorlevel%
  )
)

where python >nul 2>nul
if %errorlevel%==0 (
  python -c "import sys; sys.exit(0 if sys.version_info[0] >= 3 else 1)" >nul 2>nul
  if %errorlevel%==0 (
    python "%~dp0pre_delegate.py" %*
    exit /b %errorlevel%
  )
)

echo Python 3 was not found. Install Python 3.6+ or ensure py -3/python3 is on PATH. 1>&2
exit /b 127
""", encoding="utf-8")
    print_success("Created Windows wrapper: delegate.bat")
    
    # PowerShell wrapper
    wrapper_ps1 = hooks_dir / "delegate.ps1"
    wrapper_ps1.write_text("""# Delegation wrapper script
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$PythonCommands = @(
    @{ Command = "py"; Prefix = @("-3") },
    @{ Command = "python3"; Prefix = @() },
    @{ Command = "python"; Prefix = @() }
)

foreach ($Python in $PythonCommands) {
    if (-not (Get-Command $Python.Command -ErrorAction SilentlyContinue)) {
        continue
    }

    & $Python.Command @($Python.Prefix + @("-c", "import sys; sys.exit(0 if sys.version_info[0] >= 3 else 1)")) *> $null
    if ($LASTEXITCODE -ne 0) {
        continue
    }

    & $Python.Command @($Python.Prefix + @("$ScriptDir/pre_delegate.py") + $args)
    exit $LASTEXITCODE
}

Write-Error "Python 3 was not found. Install Python 3.6+ or ensure py -3/python3 is on PATH."
exit 127
""", encoding="utf-8")
    print_success("Created PowerShell wrapper: delegate.ps1")


def create_claude_settings(base_dir: Path):
    """Merge the delegation guard PreToolUse hook into settings.json.

    Registers the guard for both Bash and PowerShell matchers so it fires
    regardless of which shell tool Claude uses. Derives the hook path from
    the directory name (.claude or .Codex) so the command is always correct.
    """
    settings_path = base_dir / "settings.json"
    hook_root = base_dir.name  # ".claude" or ".Codex"
    command = (
        f'powershell -NoProfile -ExecutionPolicy Bypass -File "{hook_root}/hooks/delegation_guard.ps1"'
        if os.name == "nt"
        else f"python3 {hook_root}/hooks/delegation_guard.py"
    )
    hook_def = {"type": "command", "command": command, "timeout": 5}

    def is_guard_hook(hook: Dict) -> bool:
        if not isinstance(hook, dict):
            return False
        cmd = hook.get("command", "")
        return "delegation_guard.py" in cmd or "delegation_guard.ps1" in cmd

    settings = {}
    if settings_path.exists():
        try:
            settings = json.loads(settings_path.read_text(encoding="utf-8"))
        except (OSError, ValueError):
            settings = {}
    if not isinstance(settings, dict):
        settings = {}

    hooks = settings.setdefault("hooks", {})
    if not isinstance(hooks, dict):
        hooks = {}
        settings["hooks"] = hooks

    pre_tool_use = hooks.setdefault("PreToolUse", [])
    if not isinstance(pre_tool_use, list):
        pre_tool_use = []
        hooks["PreToolUse"] = pre_tool_use

    # Remove all existing guard hooks so we can re-add them cleanly
    for entry in pre_tool_use:
        if isinstance(entry, dict) and isinstance(entry.get("hooks"), list):
            entry["hooks"] = [h for h in entry["hooks"] if not is_guard_hook(h)]

    # Ensure both Bash and PowerShell matchers have the guard
    matchers_needed = {"Bash", "PowerShell"}
    for entry in pre_tool_use:
        if isinstance(entry, dict) and entry.get("matcher") in matchers_needed:
            if isinstance(entry.get("hooks"), list):
                entry["hooks"].append(hook_def)
                matchers_needed.discard(entry["matcher"])

    for matcher in matchers_needed:
        pre_tool_use.append({"matcher": matcher, "hooks": [hook_def]})

    new_content = json.dumps(settings, indent=2) + "\n"
    if settings_path.exists() and settings_path.read_text(encoding="utf-8") == new_content:
        return

    if settings_path.exists():
        timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S_%f")
        backup_path = settings_path.with_name(f"settings.json.bak.{timestamp}")
        shutil.copy2(settings_path, backup_path)

    settings_path.write_text(new_content, encoding="utf-8")
    print_success(f"Updated {hook_root}/settings.json delegation guard (Bash + PowerShell)")


def build_routing_presets(config: Dict) -> Dict:
    """Build smart routing presets based on enabled CLIs."""
    presets = {}
    
    cli_configs = config.get("cli_configs", {})
    
    # Security tasks
    if "gemini" in cli_configs:
        presets["security_audit"] = {
            "cli": "gemini",
            "pattern": "(security|vulnerability|audit|xss|sql injection|csrf)",
            "template": "shell"
        }
    
    # Git operations
    if "aider" in cli_configs:
        presets["git_operations"] = {
            "cli": "aider",
            "pattern": "(git|commit|branch|merge|rebase)",
            "template": "shell"
        }
    
    # Web search
    if "gemini" in cli_configs:
        presets["web_search"] = {
            "cli": "gemini",
            "pattern": "(search|documentation|lookup|find.*docs)",
            "template": "docs"
        }
    
    # Code analysis
    if "gemini" in cli_configs:
        presets["code_analysis"] = {
            "cli": "gemini",
            "pattern": "(analyze|review|inspect).*code",
            "template": "analyze"
        }
    
    return presets


def _build_claude_md_body(config: Dict, presets: Dict) -> str:
    """Return the managed delegation body for AGENTS.md, built from live config."""
    enabled_clis = config.get("cli_configs", {})

    if not enabled_clis:
        return (
            "## Gemini Delegation\n\n"
            "No external CLIs configured. Run `python3 setup.py` to enable delegation."
        )

    cli_list = "\n".join(
        f"- **{v['name']}**: {v['description']}" for v in enabled_clis.values()
    )
    preset_list = "\n".join(
        f"- **{name}**: Routes to `{p['cli']}`\n  Pattern: `{p['pattern']}`"
        for name, p in presets.items()
    )

    git_ops_example = ""
    if "git_operations" in presets:
        git_ops_example = (
            "\n### Git Operations\n"
            "```bash\n"
            'PROMPT=$(./.claude/hooks/delegate "git log --oneline --since=1.week" "Finding bug introduction")\n'
            'aider -p "$PROMPT"\n'
            "```\n"
        )

    return f"""## Gemini Delegation

Gemini delegation is installed locally in `.claude/hooks` and `.Codex/hooks`.

### Enabled CLIs

{cli_list}

### Delegation Presets

{preset_list}

### Always Delegate

- Commands expected to produce more than 500 lines of output
- `npm ls`, `pip list`, `pip freeze`, and verbose dependency listings
- `git log` beyond 5 commits or broad git history analysis
- Recursive searches such as `find`, `grep -r`, or repository-wide scans
- Reading or analyzing 3 or more new files
- Security audits, vulnerability scans, XSS/SQL injection/CSRF checks
- Documentation lookup or web search. Use `--profile research` so Gemini Pro is tried before Flash.
- Broad codebase analysis, performance review, or inspection tasks

### Subagent Policy

| Subagent | Cost | Status | Rule |
|----------|------|--------|------|
| `Plan` | Low | **Allowed** | Design-only; no file reads or web calls |
| `statusline-setup` | Very low | **Allowed** | Single-purpose config; fully bounded |
| `claude-code-guide` | Medium | Allowed | Claude Code / API questions; may use WebFetch |
| `Explore` | High | **Banned** | Many file reads/greps — delegate to Gemini instead |
| `general-purpose` | High | **Banned** | Uses WebSearch/WebFetch — use Gemini `--profile research` |
| `claude` | Unpredictable | **Banned** | Catch-all; use Gemini for broad tasks |

For delegation tasks, banned operations, or large-output work: use the Gemini hooks, not Claude subagents.

### Delegation Workflow

1. **Identify task type** - Security? Git ops? Analysis?
2. **Check presets** - Is there a matching preset?
3. **Use delegation hook** - Let the hook format the prompt
4. **Execute with Gemini CLI** - Use `gemini_delegate.py`, not Claude subagents
5. **Validate response** - Check quality with the post-delegation hook

### Quick Delegation

**On Windows always use the PowerShell tool — not Bash.** Git Bash cannot
run `.ps1` scripts. When generating commands, use `PowerShell(...)` not `Bash(...)`.

**Windows (PowerShell tool):**
```powershell
& .claude/hooks/delegate_and_log.ps1 "analyze @src/ for performance issues" "Optimization task" 10
& .claude/hooks/delegate_and_log.ps1 "find current docs for X" "Research task" 10 -Profile research
```

**Unix/Mac (Bash):**
```bash
PROMPT=$(./.claude/hooks/delegate "npm ls" "Build analysis")
echo "$PROMPT" | python3 .claude/hooks/gemini_delegate.py
```
{git_ops_example}
`.claude/settings.json` registers a PreToolUse Bash guard that blocks known
high-output commands and returns delegation instructions. Keep project-specific
agent instructions outside this managed section. Re-running setup updates only
this block."""


def create_usage_examples(config: Dict, base_dir: Path):
    """Create example scripts showing delegation usage."""
    hook_root = base_dir.name
    print_header(f"Creating Usage Examples in {hook_root}")
    
    examples_dir = base_dir / "examples"
    examples_dir.mkdir(exist_ok=True)
    
    # Basic example
    basic_example = examples_dir / "basic_delegation.sh"
    basic_example.write_text(f"""#!/bin/bash
# Basic delegation example

# 1. Generate optimized prompt
PROMPT=$(python3 ../{hook_root}/hooks/pre_delegate.py \
  "npm ls --depth=0" \
  "Investigating build performance")

echo "Generated prompt:"
echo "$PROMPT"
echo ""

# 2. Execute with agy
echo "Executing with agy..."
# echo "$PROMPT" | python3 ../{hook_root}/hooks/gemini_delegate.py

# 3. Validate response (after execution)
# RESPONSE=$(echo "$PROMPT" | python3 ../{hook_root}/hooks/gemini_delegate.py)
# python3 ../{hook_root}/hooks/post_delegate.py "$RESPONSE" 10 "build-analysis"
""", encoding="utf-8")
    
    if os.name != 'nt':
        basic_example.chmod(basic_example.stat().st_mode | stat.S_IXUSR)
    
    print_success("Created basic_delegation.sh")
    
    # Advanced example
    advanced_example = examples_dir / "security_audit.sh"
    advanced_example.write_text(f"""#!/bin/bash
# Security audit example - delegates to Gemini

# Run security scan on source files
PROMPT=$(python3 ../{hook_root}/hooks/pre_delegate.py \
  "grep -r 'password' src/ && grep -r 'api.*key' src/" \
  "Pre-deployment security audit" \
  8)

echo "Running security audit..."
RESPONSE=$(echo "$PROMPT" | python3 ../{hook_root}/hooks/gemini_delegate.py)

# Validate and save results
python3 ../{hook_root}/hooks/post_delegate.py "$RESPONSE" 8 "security-audit"

echo "$RESPONSE" > security-audit-results.txt
echo "Results saved to security-audit-results.txt"
""", encoding="utf-8")
    
    if os.name != 'nt':
        advanced_example.chmod(advanced_example.stat().st_mode | stat.S_IXUSR)
    
    print_success("Created security_audit.sh")


def verify_installation(base_dir: Path, config: Dict) -> bool:
    """Verify that installation was successful."""
    print_header("Verifying Installation")
    codex_dir = base_dir.parent / ".Codex"
    agents_md = base_dir.parent / "AGENTS.md"
    root_claude_md = base_dir.parent / "CLAUDE.md"
    
    gem_dir = base_dir.parent / GEMINI_DELEGATION_DIR
    checks = [
        # Shared scripts in .gemini-delegation/
        (gem_dir / "hooks" / "gemini_delegate.py", "Gemini fallback runner"),
        (gem_dir / "hooks" / "pre_delegate.py", "Pre-delegation hook"),
        (gem_dir / "hooks" / "post_delegate.py", "Post-delegation hook"),
        (gem_dir / "hooks" / "analyze_metrics.py", "Metrics analyzer"),
        (gem_dir / "hooks" / "delegation_guard.py", "Delegation guard"),
        (gem_dir / "hooks" / "delegation_guard.ps1", "Delegation guard launcher"),
        (gem_dir / "hooks" / "delegate_and_log.ps1", "Full delegation pipeline"),
        (gem_dir / "delegation_config.json", "Shared configuration"),
        # Claude per-env shims
        (base_dir / "hooks" / "delegate.ps1", "Claude delegate shim"),
        (base_dir / "hooks" / "delegate_and_log.ps1", "Claude pipeline shim"),
        (base_dir / "hooks" / "delegation_guard.ps1", "Claude guard shim"),
        (base_dir / "CLAUDE.md", "Claude configuration"),
        (base_dir / "settings.json", "Claude settings guard"),
        # Codex per-env shims
        (codex_dir / "hooks" / "delegate.ps1", "Codex delegate shim"),
        (codex_dir / "hooks" / "delegate_and_log.ps1", "Codex pipeline shim"),
        (codex_dir / "hooks" / "delegation_guard.ps1", "Codex guard shim"),
        (codex_dir / "settings.json", "Codex settings guard"),
        # Project files
        (agents_md, "AGENTS.md delegation instructions"),
        (root_claude_md, "Root CLAUDE.md bridge"),
    ]
    
    all_passed = True
    for path, description in checks:
        if path.exists():
            print_success(f"{description}: {path}")
        else:
            print_error(f"{description} missing: {path}")
            all_passed = False

    if root_claude_md.exists():
        root_lines = root_claude_md.read_text(encoding="utf-8").splitlines()
        if root_lines == list(ROOT_CLAUDE_IMPORTS):
            print_success("Root CLAUDE.md content: @AGENTS.md")
        else:
            print_error("Root CLAUDE.md is not exactly @AGENTS.md")
            all_passed = False
    
    # Check if at least one CLI is enabled
    enabled_clis = [k for k, v in config.get("cli_configs", {}).items()]
    if enabled_clis:
        print_success(f"Enabled CLIs: {', '.join(enabled_clis)}")
    else:
        print_warning("No CLIs enabled - delegation will be limited")
    
    return all_passed


def show_next_steps(config: Dict):
    """Show user what to do next."""
    print_header("Next Steps")
    
    enabled_clis = config.get("cli_configs", {})
    
    print(f"{Colors.BOLD}1. Test the hooks:{Colors.END}")
    if os.name == "nt":
        print("   py -3 .claude\\hooks\\pre_delegate.py \"test task\" \"test context\"")
    else:
        print("   python3 .claude/hooks/pre_delegate.py \"test task\" \"test context\"")
    
    if enabled_clis:
        print(f"\n{Colors.BOLD}2. Try a delegation:{Colors.END}")
        first_cli = list(enabled_clis.keys())[0]
        first_cli_cmd = enabled_clis[first_cli]["command"]
        if os.name == "nt":
            print("   $prompt = & .claude\\hooks\\delegate.ps1 \"npm ls\" \"Test\"")
            if first_cli == "gemini":
                print("   $prompt | py -3 .claude\\hooks\\gemini_delegate.py")
                print("   .claude\\hooks\\delegate_and_log.ps1 \"npm ls\" \"Test\" 5")
            else:
                print(f"   # Send $prompt to {first_cli_cmd} using that CLI's prompt option")
        else:
            print(f"   PROMPT=$(./.claude/hooks/delegate \"npm ls\" \"Test\")")
            if first_cli == "gemini":
                print(f"   {first_cli_cmd} --model {DEFAULT_GEMINI_MODEL} -p \"$PROMPT\"")
            else:
                print(f"   # Send \"$PROMPT\" to {first_cli_cmd} using that CLI's prompt option")
    
    print(f"\n{Colors.BOLD}3. Restart Claude Code{Colors.END}")
    print("   Your delegation configuration will be active")
    
    print(f"\n{Colors.BOLD}4. Review examples:{Colors.END}")
    print("   Check .claude/examples/ and .Codex/examples/ for usage examples")
    
    print(f"\n{Colors.BOLD}5. Monitor metrics:{Colors.END}")
    if os.name == "nt":
        print("   py -3 .claude\\hooks\\analyze_metrics.py")
        print("   py -3 .Codex\\hooks\\analyze_metrics.py")
    else:
        print("   python3 .claude/hooks/analyze_metrics.py")
        print("   python3 .Codex/hooks/analyze_metrics.py")


def main():
    """Enhanced installation flow."""
    # Import from basic installer
    from install import (
        check_python_version,
        discover_clis,
        interactive_selection,
        setup_hooks,
        generate_delegation_config,
        save_config,
        extract_migrated_claude_content,
        ensure_agents_md,
        ensure_root_claude_bridge,
        ensure_dot_claude_bridge,
        install_not_found_clis
    )

    parser = argparse.ArgumentParser(
        description="Install Claude-Gemini delegation hooks and routing rules."
    )
    parser.add_argument(
        "--enable-cli",
        action="append",
        choices=("gemini", "aider", "copilot", "gpt-me"),
        dest="enabled_clis",
        help="Enable an additional delegation CLI. Repeat for multiple CLIs. Default: gemini only.",
    )
    parser.add_argument(
        "--all-clis",
        action="store_true",
        help="Enable every supported CLI that is installed.",
    )
    parser.add_argument(
        "--target",
        type=str,
        default=None,
        help="Target directory for installation (default: current working directory)",
    )
    parser.add_argument(
        "--update-all",
        action="store_true",
        help="Update all globally registered installations with the latest hook scripts.",
    )
    args = parser.parse_args()
    
    if args.update_all:
        if not HOOKS_SOURCE.exists():
            print_error(f"Hooks source directory not found: {HOOKS_SOURCE}")
            sys.exit(1)
        update_all_installations(HOOKS_SOURCE)
        sys.exit(0)
    
    print_header("Claude-Gemini Delegation Enhanced Setup")
    
    # Check Python version
    if not check_python_version():
        sys.exit(1)
    
    # Determine installation location
    if args.target:
        base_dir = Path(args.target) / ".claude"
    else:
        base_dir = Path.cwd() / ".claude"
    print_info(f"Installing to: {base_dir.absolute()}")
    
    # Discover CLIs
    discovered = discover_clis()
    
    # CLI selection. Default is Gemini only; other CLIs require explicit flags.
    enabled_cli_names = ["gemini"] + (args.enabled_clis or [])
    configured = interactive_selection(
        discovered,
        enabled_cli_names=enabled_cli_names,
        enable_all=args.all_clis,
    )
    
    # Setup hooks directory
    setup_hooks(base_dir)
    
    # Copy hook files
    # Generate config first — needed by install_gemini_delegation_dir
    config = generate_delegation_config(configured)
    presets = build_routing_presets(config)

    # Install shared scripts to .gemini-delegation/ (single copy for both envs)
    if HOOKS_SOURCE.exists():
        install_gemini_delegation_dir(base_dir.parent, config)
    else:
        print_warning(f"Hooks source directory not found: {HOOKS_SOURCE}")

    # Install per-env shims (thin forwarders to .gemini-delegation/hooks/)
    hooks_dir = base_dir / "hooks"
    setup_hooks(base_dir)
    create_env_shims(hooks_dir)
    create_claude_settings(base_dir)

    codex_dir = base_dir.parent / ".Codex"
    setup_hooks(codex_dir)
    create_env_shims(codex_dir / "hooks")
    create_claude_settings(codex_dir)

    # Make .claude/CLAUDE.md a bridge; migrate its content to AGENTS.md
    dot_claude_migrated = ensure_dot_claude_bridge(base_dir)
    root_claude_md = base_dir.parent / "CLAUDE.md"
    root_claude_existing = root_claude_md.read_text(encoding="utf-8") if root_claude_md.exists() else ""
    root_migrated = extract_migrated_claude_content(root_claude_existing)
    combined_migration = (
        root_migrated.rstrip("\n") + "\n\n" + dot_claude_migrated
        if dot_claude_migrated.strip() else root_migrated
    )
    ensure_agents_md(
        base_dir.parent,
        combined_migration,
        managed_body=_build_claude_md_body(config, presets),
    )
    ensure_root_claude_bridge(base_dir.parent)

    create_usage_examples(config, base_dir)
    create_usage_examples(config, codex_dir)

    # Install bundled agents (Dave, etc.)
    install_agents(base_dir.parent)

    # Create temp/ for delegation response files
    ensure_temp_dir(base_dir.parent)

    # Verify installation
    if not verify_installation(base_dir, config):
        print_error("Installation verification failed")
        sys.exit(1)

    # Stage generated files with git
    stage_generated_files(base_dir.parent, base_dir, codex_dir)

    # Show next steps
    show_next_steps(config)

    # Offer to install missing CLIs
    install_not_found_clis(configured)

    print_header("Installation Complete!")
    print(f"\n{Colors.GREEN}{Colors.BOLD}Your delegation setup is ready!{Colors.END}\n")


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print(f"\n\n{Colors.YELLOW}Installation cancelled.{Colors.END}")
        sys.exit(0)
    except Exception as e:
        print_error(f"Installation failed: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
